# use Java and non-root
language: Java
jdk: oraclejdk8


# install the Markdown linting program called mdl
before_install:
  - gem install mdl


# run checks on the README file with mdl and proselint
# "gradle build" will build the tool
# "gradle run.." will run the examples
script:
  # lint the assignment's documentation
  - mdl README.md
  - proselint README.md
  - gradle --version
  - gradle clean
  - gradle check
  - gradle build
  - gradle runQuadratic
  - gradle runAllZeros
  - gradle runStringOptimization
  - gradle runQuadratic --args='GeometricSearch'
  - gradle runQuadratic --args='LatticeSearch'
